### ISSUE TITLE
Add support for YAML config

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-plugin-framework-java#12]
Today, Java plugins expect Java properties file for their configuration. We should also add support for YAML, which would simplify things like region-specific configuration (https://github.com/killbill/killbill-plugin-framework-java/issues/11):

```
common: &defaults
  username: XXX
  password: YYY

us-east-1:
  <<: *defaults
  paymentUrl: ZZZ1

us-west-1:
  <<: *defaults
  paymentUrl: ZZZ2
```
